### ISSUE TITLE
Environment&DataPreparation

### ISSUE THREAD

**Issue by vitrigut** [ironhack-bcn-data-june-2020/project-ml-bank-churn#3]
Be aware of outliers!

**Comment by AnnaVilardell** [comment]
**Churn_Modeling** - original (raw data)
**Churn_Clean** - limpio  (clean data): después de Data Wrangling (Explore Data, Clean Data y Transform Data) &  Feature Selection.
**Churn_norm** - (normalized data): es el que la data está con MinmaxSlacer aplicado y listo para usar con los modelos

**Comment by AnnaVilardell** [comment]
Después de la conversación con Alberto, quedamos en modificar / añadir:

- outliers - @cucu-o0  MISSING
- new column con 0 y 1 Balance0 - @AnnaVilardell  DONE
-  remove 1 column of country (drop_first=True) - @AnnaVilardell  DONE
- remove csv con log, we just leave is as done in the notebook. - @AnnaVilardell  DONE
- MinmaxSacler (entre 0 y 1) instead of StandardScaler - @AnnaVilardell  DONE
- PCA al final y visualizar - Anna MISSING (Vero puedes @cucu-o0  tu?)
